- name: Add opensips-cli key
  shell: 'curl https://apt.opensips.org/pubkey.gpg | apt-key add -'

- name: Add opensips-cli reposity
  template:
    src: "{{ item }}.j2"
    dest: "{{ sources_list_dir }}/{{ item }}"
    backup: true
  with_items: "{{ opensips_cli_source_list_file }}"

- name: Install opensips-cli
  apt:
    update_cache: yes
    name: "opensips-cli"
    state: present