- name  : Remove old cronjob
  shell : crontab -r

- name: Export log job.
  cron:
    name: "Export Job"
    user: "root"
    minute: 30
    hour: 21
    job: "/bin/export_report"
    state: present

- name: Truncate db.
  cron:
    name: "Truncate db"
    user: "root"
    minute: 35
    hour: 21
    job: "/bin/truncate_db"
    state: present

- name: Rotate log.
  cron:
    name: "Rotate log"
    user: "root"
    minute: 59
    hour: 23
    job: "/usr/sbin/logrotate -f /opt/logrotate/ops"
    state: present

- name: Stop sip-on-docker.
  cron:
    name: "Stop sip-on-docker"
    user: "root"
    minute: 45
    hour: 21
    job: "docker-compose -f /root/sip-on-docker/docker-compose.yaml stop"
    state: present

- name: Start sip-on-docker.
  cron:
    name: "Start sip-on-docker"
    user: "root"
    minute: 0
    hour: 1
    job: "docker-compose -f /root/sip-on-docker/docker-compose.yaml restart"
    state: present
