- name: Opensips | Clone repo
  git:
    repo: "{{ opensips_cp_repo }}"
    dest: "{{ opensips_cp_dir }}"
    force: yes
    version: "{{ opensips_cp_version }}"

- name: Apache2 config for opensips_cp
  copy:
    src: "apache2.conf"
    dest: "/etc/apache2/apache2.conf"

- name: Config opensips_cp cdrviwer
  copy:
    src: "local.inc.php"
    dest: "/var/www/html/opensips-cp/config/tools/system/cdrviewer/local.inc.php"

- name: Config db.inc opensips_cp
  copy:
    src: "db.inc.php"
    dest: "/var/www/html/opensips-cp/config/db.inc.php"

- name: Opensips | boxes.global.inc config.
  copy:
    src: "boxes.global.inc.php"
    dest: "/var/www/html/opensips-cp/config/boxes.global.inc.php"

- name: Opensips | CP file permission
  shell: "chown -R www-data:www-data /var/www/html/opensips-cp"

- name: GET fix_ops_cp script
  copy:
    src: "fix_ops_cp.py"
    dest: "/opt/fix_ops_cp.py"

- name: Execute fix_ops_cp
  shell: "python3 /opt/fix_ops_cp.py"