---

- name: Disable apache2
  service: 
    name: apache2
    state: stopped
    enabled: false
    
- name: Disable kubelet
  service: 
    name: kubelet
    state: stopped
    enabled: false

- name: Restart prometheus
  service:
    name: prometheus
    state: restarted
